### PR TITLE
Fix for ItemStand Altars

### PR DESCRIPTION
**Pull request by Wacky-Mole**
I have fixed t4 and t5 boss altars. Because of the change in json file, I would recommend changing it to {ModGUID}2.json file or saving the version somehow. 
-Cheers -WM

### CODE REVIEW

**Comment by swolewizard** [comment]
I inputted your code into my project and compiled it to test it out in-game, I'm unable to attach anything to the GoblinKing / Dragonqueen altar locations, it's giving the debug response of "This is not a support Type" when using the intended default item and "CanAttach IsSupported is false" with an unintended item.

It has also seemed to have broken all other item stands, for example the ones you craft with a hammer, They're unable to attach anything.

Not sure if I'm doing anything wrong on my end but the code doesn't seem to work for me.

**Comment by Wacky-Mole** [comment]
I tested and Majestic tested and I think it is good now. Let me know if you discover anything else.

**Comment by swolewizard** [comment]
So this code works for me right now, the only problem which I don't mind, is when the location is first spawned in only one of the item stands is changed to allow the customizable SacrificeItem. It only works for all item stands when the location is loaded out of game scene and back in, for example dragonqueen's location 3 item stands. not really a huge problem but if it's something you can apply a quick fix for might aswell.

Other than that, if you could review the changes I've made and remove all unnecessary debug/code and only leave what's needed to work, I can merge and submit to nexus/thunderstore.

**Comment by Wacky-Mole** [comment]
Code review looks good.  I have started the game from both t4 and t5 boss and haven't seen that issue.  Are you talking about with like console spawning or Infinity hammer spawning of the altars? If that's the case then, a user shouldn't ever seen the issue.  It would be more than just a patch to awake to fix then, you would have to patch UseItem, which I was doing earlier, but found it unnecessary.

**Pull request merged**
